/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ph_edu_dlsu_Hello */

#ifndef _Included_ph_edu_dlsu_Hello
#define _Included_ph_edu_dlsu_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ph_edu_dlsu_Hello
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ph_edu_dlsu_Hello_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
